// Task 1
// function sum(a,b){
//     return a+b
// }
// console.log(sum(2,3));
// console.log(sum(4,4));
// console.log(sum(-2,4));


// Task 2
// function checkNumber(a){
//     return a>0? "Positive": a<0? "Negative" :"Zero" 
// }
// console.log(checkNumber(5));
// console.log(checkNumber(-5));
// console.log(checkNumber(0));


// Task 3
// function generateMultiplicationTable(a) {
//   for (let i = 1; i <= 10; i++) {
//     console.log(`${a} * ${i} = ${a * i}`);
//   }
// }
// console.log(generateMultiplicationTable(5));


// TAsk 4
// function endNine(a){
//     return a%10==9?"Yes":"No"
// }
// console.log(endNine(149));
// console.log(endNine(387));
// console.log(endNine(29));
 

// Task 5
// function century(n){
//     return n/100
// } 
// console.log(century(1800))
// console.log(century(1900))
// console.log(century(2000))


// Task 6
// function calculateCircleArea(a) {
//   return `The area of a circle with radius ${a} is ${Math.ceil(3.14 * a * a)}`
// }
// console.log(calculateCircleArea(5))
// console.log(calculateCircleArea(8))
// console.log(calculateCircleArea(3))


// Task 7
// function sum3Digit(n){
//     let a=n/100;
//     let b=n/10%10;
//     let c=n%10;
//     return Math.floor(a+b+c)
// }
// console.log(sum3Digit(123))
// console.log(sum3Digit(345))
// console.log(sum3Digit(321))


// Task 8
// function sumOfDigits(n){
//     return n>0?n+1:n-2
// }
// console.log(sumOfDigits(22))
// console.log(sumOfDigits(4))
// console.log(sumOfDigits(3))


// Task 9
// function lessThan100(n,m){
//     return n+m<100?"True":"False"
// }
// console.log(lessThan100(22,15))
// console.log(lessThan100(83,34))
// console.log(lessThan100(3,77))


// Task 10
// function longestTime(v,n,m){
//     let a = v * 3600
//     let b = n * 60
//     let c = m 
//     if(a>b&&a>c) return a/3600 
//     if(b>a&&b>c) return b/60 
//     if(c>a&&c>b) return c 
// }
// console.log(longestTime(1, 59, 3598))
// console.log(longestTime(2, 300, 15000))
// console.log(longestTime(15, 955, 59400))
